baseURL = 'https://minsoehan.pages.dev/'
languageCode = 'en-us'
title = 'Min Soe Han'

[minify]
    minifyOutput = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true
                title = true

[menus]
    [[menus.main]]
        name = 'Tech'
        pageRef = '/tech'
        weight = 1
    [[menus.main]]
        name = 'Legal'
        pageRef = '/legal'
        post = '<i class="fa-solid fa-chevron-down has-children-indicator"></i>'
        weight = 2
    [[menus.main]]
        name = 'Labor Laws'
        pageRef = '/legal/labor-laws'
        parent = 'Legal'
        weight = 1
    [[menus.main]]
        name = 'Investment'
        pageRef = '/legal/investment'
        parent = 'Legal'
        weight = 2
    [[menus.main]]
        name = 'Open Diary'
        pageRef = '/open-diary'
        weight = 3
    [[menus.main]]
        name = 'Others'
        pageRef = '/others'
        weight = 4
    [[menus.main]]
        name = 'About'
        pageRef = '/about'
        weight = 5
